apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca
  namespace: cert-manager
spec:
  duration: 43800h # 5 years
  subject:
    organizations:
      - Geeks R Us
    organizationalUnits:
      - IT Department
    countries:
      - InterWebs
    provinces:
      - K8
    localities:
      - Basement
  isCA: true
  commonName: "home.lab"
  secretName: homelab-ca
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io


---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: homelab-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab
  namespace: cert-manager
spec:
  duration: 43800h # 5 years
  commonName: "*.home.lab"
  secretName: homelab
  renewBefore: 72h
  subject:
    organizations:
      - Geeks R Us
    organizationalUnits:
      - IT Department
    countries:
      - InterWebs
    provinces:
      - K8
    localities:
      - Basement 
  issuerRef:
    name: homelab-ca-issuer
    kind: Issuer
    group: cert-manager.io

  